require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit
RSpec/NamedSubject:
  EnforcedStyle: always

RSpec/AnyInstance:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
